 version: '3'

 services:
   nginx:
     image: nginx
     container_name: nginx
     restart: always
     volumes:
       - ../ghost/nginx.conf:/etc/nginx/conf.d/ghost.conf
     ports:
       - "80:80"
