 version: '3'

 services:
   ghost-blog:
     image: ghost
     container_name: ghost-blog
     restart: always
     environment:
       NODE_ENV: 'production'
     volumes:
       - ./blog:/var/lib/ghost
     ports:
       - "127.0.0.1:10080:2368"
